Desktop/group22proj-gdpr_requirements/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get '/home/live_chat', to: 'home#live_chat', as: :home_live_chat
  get '/contests/:id/evaluate', to: 'contests#evaluate', as: :contest_evaluate
  post '/contests/:id/evaluate', to: 'contests#submit_ranking', as: :contest_submit_ranking
  get '/connect/oauth', to: 'home#my_contests', as: :contest_connect_stripe

  get 'sessions/create'
  get 'sessions/destroy'

  resources :contests do
    resources :submissions, only: [:index, :new, :create, :destroy]
    resources :videos, only: [:new, :create, :destroy]
  end

  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  root 'home#home'
  get '/leaderboard', to:'home#leaderboard'
  get '/my_contests', to: 'home#my_contests'
  get '/my_submissions', to: 'home#my_submissions'
  get '/home', to: 'home#home'
  get '/users', to: 'home#home'
  #how does submission routing work?
  # get '/submission'
  # get '/like' ??
  #

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Desktop/group22proj-gdpr_requirements/app/models/contest.rb
class Contest < ApplicationRecord

  validates :name, presence: true
  validates :description, presence: true
  validates :category, presence: true
  validates :payout_amount, presence: true, numericality: {greater_than_or_equal_to: 100, less_than_or_equal_to: 299999700,
                                                           message: "must be least £4.00 and should not exceed £2,999,997.00"}
  validates :first_prize, presence: true, numericality: {greater_than_or_equal_to: 100, less_than_or_equal_to: 99999900,
                                                         message: "must be least £2.00 and should not exceed £999,999.00"}
  validates :second_prize, presence: true, numericality: {greater_than_or_equal_to: 100, less_than_or_equal_to: 99999900,
                                                          message: "must be least £1.00 and should not exceed £999,999.00"}
  validates :third_prize, presence: true, numericality: {greater_than_or_equal_to: 100, less_than_or_equal_to: 99999900,
                                                         message: "must be least £1.00 and should not exceed £999,999.00"}
  # should not in the future
  validates :start_date, presence: true

  # should not be in the past
  validates :ending_date, presence: true

  validate :payouts_add_up
  validate :payouts_hierarchy
  validate :selected_winners
  # validate :min_duration
  # validate :deny_payout_changes

  has_many :submissions, dependent: :destroy
  has_many :videos, dependent: :destroy
  belongs_to :user


  def ending_on
    ending_date.in_time_zone(Time.zone).strftime("%d/%m/%Y %H:%M")
  end

  def has_ended
    Time.current > ending_date
  end

  def show_payout
    amount = (self.payout_amount).to_f
    '%.2f' % (amount / 100.0)
  end

  def show_first_prize
    amount = self.first_prize.to_f
    '%.2f' % (amount / 100.0)
  end

  def show_second_prize
    amount = self.second_prize.to_f
    '%.2f' % (amount / 100.0)
  end

  def show_third_prize
    amount = self.third_prize.to_f
    '%.2f' % (amount / 100.0)
  end

  private

  def payouts_add_up
    if first_prize + second_prize + third_prize != payout_amount
      errors.add(:payout_amount, 'error: Prizes should add up to the total Payout amount!')
    end
  end

  def payouts_hierarchy
    if second_prize >= first_prize
      errors.add(:second_prize, 'error: 2nd Place Prize should not exceed 1st Place Prize!')
    elsif third_prize > second_prize
      errors.add(:third_prize, 'error: 3rd Place Prize must be less than or equal to 2nd Place Prize!')
    elsif third_prize > first_prize
      errors.add(:third_prize, 'error: 3rd Place Prize should not exceed 1st Place Prize!')
    end
  end

  def selected_winners
    if !first_place.nil? || !second_place.nil? || !third_place.nil?
      if first_place == second_place || first_place == third_place
        errors.add(:first_place, 'error: a user cannot be selected for more than 1 place')
      elsif second_place == third_place
        errors.add(:second_place, 'error: a user cannot be selected for more than 1 place')
      end
    end
  end

  # def min_duration
  #   # date_start = Date.parse(ending_date)
  #   # date_now = Date.today
  #   # days_passed = (Date.today - date_sent).to_i
  #   if ending_date < (DateTime.now + 7.days)
  #     errors.add(:ending_date, 'error: must be at least 7 days from today.')
  #   end
  # end
  #
  # def deny_payout_changes
  #   if payout_amount_changed? && self.persisted?
  #     errors.add(:payout_amount, 'cannot be changed after creating a contest.')
  #   end
  # end

end

Desktop/group22proj-gdpr_requirements/app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_action :set_contest, only: [:show, :edit, :update, :destroy, :evaluate, :submit_ranking]
  before_action :require_same_user, only: [:edit, :update, :destroy, :evaluate, :submit_ranking]
  before_action :authenticate_user!, :except => [:show, :index]

  # GET /contests
  # GET /contests.json
  def index
    # find and retrieve only the contests that have been paid & has not ended
    # @contests2 = Contest.where(paid_for: true).order('updated_at DESC').select {|c| c.has_ended }
    contest_category = params[:category]
    if !contest_category.nil?
      @contests = Contest.where(paid_for: true, category: contest_category).where("ending_date > '#{Time.now.utc.iso8601}'").order('updated_at DESC')
      @past_contests = Contest.all.where(paid_for: true, evaluated: true, category: contest_category).where("ending_date <= '#{Time.now.utc.iso8601}'").order('updated_at DESC')
    else
      @contests = Contest.where(paid_for: true).where("ending_date > '#{Time.now.utc.iso8601}'").order('updated_at DESC')
      @past_contests = Contest.all.where(paid_for: true, evaluated: true).where("ending_date <= '#{Time.now.utc.iso8601}'").order('updated_at DESC')
    end

  end

  def evaluate
    @contest = Contest.find(params[:id])
    @submissions = Submission.all.where(contest_id: @contest.id)
  end

  def submit_ranking
    # add check number of submissions before processing transfer
    @contest = Contest.find(params[:id])
    @submissions = Submission.all.where(contest_id: @contest.id)
    if !@submissions.empty?
      if @contest.has_ended && !@contest.evaluated && @contest.paid_for
        respond_to do |format|
          if @contest.update(ranking_params)
            @first_place_user = User.find_by_id(@contest.first_place.to_i)
            @first_place_user.contests_won += 1
            @first_place_user.save
            transfer = Stripe::Transfer.create({
                                                   amount: (@contest.first_prize.to_i),
                                                   currency: 'GBP',
                                                   destination: @first_place_user.stripe_id,
                                                   transfer_group: '{ORDER10}',
                                               })

            if !@contest.second_place.nil?
              @second_place_user = User.find_by_id(@contest.second_place.to_i)

              @second_place_user.contests_won += 1
              @second_place_user.save
              transfer2 = Stripe::Transfer.create({
                                                      amount: (@contest.second_prize.to_i),
                                                      currency: 'GBP',
                                                      destination: @second_place_user.stripe_id,
                                                      transfer_group: '{ORDER10}',
                                                  })
              if !@contest.third_place.nil?
                @third_place_user = User.find_by_id(@contest.third_place.to_i)
                @third_place_user.contests_won += 1
                @third_place_user.save
                transfer3 = Stripe::Transfer.create({
                                                        amount: (@contest.third_prize.to_i),
                                                        currency: 'GBP',
                                                        destination: @third_place_user.stripe_id,
                                                        transfer_group: '{ORDER10}',
                                                    })
              end
            end
            @contest.evaluated = true
            @contest.save
            format.html { redirect_to @contest, notice: 'Ranking saved. Contest prize money have paid out to the selected users!' }
          else
            format.html { render :evaluate }
          end
        end
      elsif !@contest.paid_for
        redirect_to contests_path, alert: 'You have not deposited funds to pay out the successful participant(s) for this contest.'
      elsif @contest.evaluated
        redirect_to contests_path, alert: 'You have already paid out prize money to the successful participant(s).'
      else
        redirect_to contest_path, alert: 'You can only payout the prize money once this contest has ended.'
      end
    else
      redirect_to contests_path, alert: 'You cannot rank a contest with no submissions.'
    end
  end


  # GET /contests/1
  # GET /contests/1.json
  def show
    if current_user
      state = current_user.authenticatable_salt
      @stripe_btn_url = "https://connect.stripe.com/express/oauth/authorize?client_id=ca_H77EPzbfQs9D9Ickbf94U4uMt9feQCKY&state=#{state}&stripe_user[email]=#{current_user.email}"
      if params.has_key?(:success)
        if params[:success] == 'true'
          verify_payment
        else
          flash[:alert] = 'Deposit for Contest Payout was cancelled.'
        end
      end


      unless @contest.paid_for
        @session = Stripe::Checkout::Session.create(
            payment_method_types: ['card'],
            line_items: [{
                             name: @contest.name,
                             description: 'Contest Payout Deposit',
                             amount: @contest.payout_amount,
                             currency: 'gbp',
                             quantity: 1,
                         }],
            success_url: contest_url(id: @contest.id, success: true),
            cancel_url: contest_url(id: @contest.id, success: false),
            client_reference_id: @contest.id
        )
      end
    end

    if @contest.evaluated
      @winner_1st = User.find_by(id: @contest.first_place)
      @winner_2nd = User.find_by(id: @contest.second_place)
      @winner_3rd = User.find_by(id: @contest.third_place)
    end
    @contest = Contest.find(params[:id])
    @videos = Video.all.where(contest_id: @contest.id)
  end

  # GET /contests/new
  def new
    @contest = current_user.contests.build
    @contest.user = current_user
  end

  # GET /contests/1/edit
  def edit
  end

  # POST /contests
  # POST /contests.json
  def create

    @contest = current_user.contests.new(contest_params)

    respond_to do |format|
      if @contest.save
        format.html { redirect_to my_contests_path, notice: 'Your Contest has been created! Deposit funds to start your contest.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /contests/1
  # PATCH/PUT /contests/1.json
  def update
    @contest = Contest.find(params[:id])
    respond_to do |format|
      if @contest.update(contest_params)
        format.html { redirect_to @contest, notice: 'Contest was successfully updated.' }
      end
    else
      format.html { render :edit }
    end
  end


  # DELETE /contests/1
  # DELETE /contests/1.json
  def destroy
    @contest.destroy
    respond_to do |format|
      format.html { redirect_to contests_url, notice: 'Contest was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contest
    @contest = Contest.find(params[:id])
  end

  def params_decimal_to_int(params_in, keys)
    keys.each do |key|
      params_in[key] = BigDecimal(params_in[key]) * 100
    end
    params_in
  end

  # Only allow a list of trusted parameters through.
  def contest_params
    if defined? @contest
      params_decimal_to_int(
          params.require(:contest).permit(:name, :description, :category, :first_prize, :second_prize,
                                          :third_prize, :start_date, :ending_date, :is_student_only),
          [:first_prize, :second_prize, :third_prize]
      )

    else
      params_decimal_to_int(
          params.require(:contest).permit(:name, :description, :category, :payout_amount, :first_prize, :second_prize,
                                          :third_prize, :start_date, :ending_date, :is_student_only),
          [:payout_amount, :first_prize, :second_prize, :third_prize]
      )
    end

  end

  def ranking_params
    params.require(:contest).permit(:first_place, :second_place, :third_place)
  end

  def require_same_user
    if current_user != @contest.user
      flash[:alert] = 'You do not have permissions to perform this action.'
      redirect_to contests_path
    end
  end

  def verify_payment
    events = Stripe::Event.list({
                                    type: 'checkout.session.completed',
                                    created: {
                                        # Check for events created in the last 24 hours.
                                        gte: Time.now.utc.to_i - 24 * 60 * 60,
                                    },
                                })

    events.auto_paging_each do |event|
      session = event['data']['object']
      if session.client_reference_id.to_i == @contest.id
        @contest.paid_for = true
        @contest.save
        flash[:notice] = 'Funds successfully deposited for Contest.'
      end
    end
  end


end

Desktop/group22proj-gdpr_requirements/app/helpers/contests_helper.rb
module ContestsHelper
end

Desktop/group22proj-gdpr_requirements/app/views/contests/edit.html.erb
<div>
  <%= link_to "Back to Contests", contests_path, class: "btn btn-secondary mt-3" %>
</div>


<div class="page-heading">
  <h2>Editing Contest</h2>
</div>

<%= render 'form', contest: @contest %>

Desktop/group22proj-gdpr_requirements/app/views/contests/evaluate.html.erb
<div>
  <%= link_to "Back to Contests", contests_path, class: "btn btn-secondary" %>
</div>

<div class="page-heading">
  <h2>Evaluating Contest</h2>
</div>


<%= form_for :contest, url: contest_evaluate_path do |form| %>

  <div class="font-weight-bold indigo-text mr-2 mt-1">1st Place:</div>

  <div class="form-group">
    <%= form.select(:first_place, @submissions.collect { |s| [s.user.username, s.user.id] }, {}, class: "form-control", id: 'first-place-select') %>
  </div>

  <% if @submissions.size >= 2 %>
    <div class="font-weight-bold indigo-text mr-2 mt-1">2nd Place:</div>
    <div class="form-group">
      <%= form.select(:second_place, @submissions.collect { |s| [s.user.username, s.user.id] }, {}, class: "form-control", id: 'second-place-select') %>
    </div>
    <% if @submissions.size >= 3 %>
      <div class="font-weight-bold indigo-text mr-2 mt-1">3rd Place:</div>
      <div class="form-group">
        <%= form.select(:third_place, @submissions.collect { |s| [s.user.username, s.user.id] }, {}, class: "form-control", id: 'third-place-select') %>
      </div>
    <% end %>
  <% end %>

  <div class="submissions-table">
    <table class="table">
      <thead>
      <tr>
        <th scope="col">Submission No.</th>
        <th scope="col">Username</th>
        <th scope="col">View</th>
      </tr>
      </thead>
      <tbody>

      <% @submissions.each do |submission| %>
        <tr>
          <td><%= submission.id %></td>
          <td><%= submission.user.username %></td>
          <td><%= link_to "Download", submission.attachment_url, class: "btn btn-secondary download" %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>


  <div>
    <%= form.submit "Submit Payout to Users", class: "btn btn-success" %>
  </div>


<% end %>

Desktop/group22proj-gdpr_requirements/app/views/contests/index.html.erb
<div class="page-heading">
  <h2>Ongoing Contests</h2>
</div>
<% if @contests.empty? %>
  <h5 class="no-contest mt-4 mb-5 text-muted">
    <strong>No active contest found for this category. Be the first user to start one!</strong>
    <div>
      <%= link_to "Create New Contest", new_contest_path, class: "btn btn-success mt-3 mb-5", id: "create_new" %>
    </div>
  </h5>
<% else %>
  <%= link_to "Create New Contest", new_contest_path, class: "btn btn-success mt-3 mb-3", id: "create_new" %>
  <div class="row">
    <% @contests.each do |contest| %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-3 p-3 mb-1">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= contest.name %></h5>
            <p>
              <h6 class="card-subtitle mb-2 text-muted ">created by: <%= contest.user.username %></h6>
            </p>
            <p class="card-text"><%= contest.description %></p>
            <div>
              <span class="badge badge-price p-2 mt-2">£<%= number_with_delimiter(contest.show_payout, :delimiter => ',', :precision => '2') %></span>
              <% if contest.is_student_only == true %>
                <span class="badge badge-primary p-2 mt-2" style="color: white "><strong>Students Only</strong></span>
              <% end %>
            </div>
            <p class="badge-ending-date">Ends on: <%= contest.ending_on %></span></p>
            <% if current_user %>
              <% if current_user == contest.user %>
                <div class="d-flex">
                  <%= link_to "View", contest, class: "btn btn-secondary w-50 mr-2" %>
                  <% if !contest.has_ended %>
                    <%= link_to "Edit", edit_contest_path(contest), class: "btn btn-secondary w-50 mr-2" %>
                  <% elsif !contest.evaluated %>
                    <%= link_to 'Payout', contest_evaluate_path(contest), class: "btn btn-primary w-50 mr-2" %>
                  <% end %>
                </div>
              <% elsif current_user != contest.user %>
                <% if !contest.has_ended %>
                  <div class="d-flex">
                    <%= link_to "View", contest, class: "btn btn-secondary w-50 mr-2" %>
                    <%= link_to 'Enter', new_contest_submission_path(contest), class: "btn btn-success w-50 mr-2" %>
                  </div>
                <% end %>
              <% end %>
            <% else %>
              <%= link_to "View", contest, class: "btn btn-secondary w-100" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<div class="page-heading mt-4">
  <h2>Past Contests</h2>
</div>
<% if !@past_contests.empty? %>

  <div class="past-contests-container">
    <div class="row">
      <% @past_contests.each do |contest| %>
        <div class="col-12 col-sm-6 col-md-4 col-lg-3 p-3 mb-1">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title"><%= contest.name %></h5>
              <p>
                <h6 class="card-subtitle mb-2 text-muted">created by: <%= contest.user.username %></h6>
              </p>
              <p class="card-text"><%= contest.description %></p>
              <div>
                <span class="badge badge-price p-2 mt-2">£<%= number_with_delimiter(contest.show_payout, :delimiter => ',', :precision => '2') %></span>
                <% if contest.is_student_only == true %>
                  <span class="badge badge-primary p-2 mt-2" style="color: white "><strong>Students Only</strong></span>
                <% end %>
              </div>
              <p class="badge-ending-date">Ends on: <%= contest.ending_on %></span></p>
              <%= link_to "View", contest, class: "btn btn-secondary w-100" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <h5 class="no-contest mt-4 mb-5 text-muted">
    <strong>No past contests found for this category.</strong></h5>
<% end %>

Desktop/group22proj-gdpr_requirements/app/views/contests/new.html.erb
<div>
  <%= link_to "Back to Contests", contests_path, class: "btn btn-secondary" %>
</div>

<div class="page-heading">
  <h2>Create Contest</h2>
</div>

<%= render 'form', contest: @contest %>

<%= link_to 'Back', contests_path %>

Desktop/group22proj-gdpr_requirements/app/views/contests/show.html.erb
<%= link_to "Back to Category", contests_path, class: "btn btn-secondary mt-4 mb-3" %>

<p class="contest-text">
  <strong>Name:</strong>
  <%= @contest.name %>
</p>

<p class="contest-text">
  <strong>Description:</strong>
  <%= @contest.description %>
</p>

<p class="contest-text">
  <strong>Category:</strong>
  <%= @contest.category %>
</p>

<p class="contest-text">
  <strong>Payout: </strong>£<%= number_with_delimiter(@contest.show_payout, :delimiter => ',', :precision => '2') %>
</p>


<div class="text mt-3">
  <% if !@contest.evaluated %>
    <p class="contest-text">
      <strong>1st Place
        Prize: </strong>£<%= number_with_delimiter(@contest.show_first_prize, :delimiter => ',', :precision => '2') %>
    </p>
  <% elsif @contest.evaluated && !@contest.first_place.nil? %>
    <p class="contest-text"><strong>1st Place: <%= @winner_1st.username %> -
      £<%= number_with_delimiter(@contest.show_first_prize, :delimiter => ',', :precision => '2') %></strong></p>
  <% end %>
</div>

<div class="text mt-3">
  <% if !@contest.evaluated %>
    <p class="contest-text">
      <strong>2nd Place
        Prize: </strong>£<%= number_with_delimiter(@contest.show_second_prize, :delimiter => ',', :precision => '2') %>
    </p>
  <% elsif @contest.evaluated && !@contest.second_place.nil? %>
    <p class="contest-text"><strong>2nd Place: <%= @winner_2nd.username %> -
      £<%= number_with_delimiter(@contest.show_second_prize, :delimiter => ',', :precision => '2') %></strong></p>
  <% end %>
</div>

<div class="text mt-3">
  <% if !@contest.evaluated %>
    <p class="contest-text"><strong>3rd Place
      Prize: </strong>£<%= number_with_delimiter(@contest.show_third_prize, :delimiter => ',', :precision => '2') %>
    </p>
  <% elsif @contest.evaluated && !@contest.third_place.nil? %>
    <p class="contest-text"><strong>3rd Place: <%= @winner_3rd.username %> -
      £<%= number_with_delimiter(@contest.show_third_prize, :delimiter => ',', :precision => '2') %></strong></p>
  <% end %>
</div>

<div>
  <p class="contest-text">
    <strong>Starts: </strong><%= @contest.start_date %>
  </p>
</div>

<p class="contest-text">
  <strong>Ends on:</strong>
  <%= @contest.ending_date %>
</p>

<% if @contest.is_student_only %>
  <h6><strong>Students Only!</strong></h6>
<% end %>

<div class="d-flex mt-3">
  <%= link_to 'View Entries', contest_submissions_path(@contest), class: "btn btn-secondary mb-1 w-50" %>
</div>

<!--if vendor or admin:-->
<% if (current_user && current_user == @contest.user) || (current_user && current_user.admin?) %>

  <div class="d-flex">
    <% if @contest.has_ended && @contest.paid_for && !@contest.evaluated %>
      <%= link_to 'Evaluate', contest_evaluate_path(@contest.id), class: "btn btn-secondary w-50 mb-1" %>
    <% end %>
  </div>

  <div class="d-flex">
    <% if !@contest.has_ended %>
      <%= link_to 'Add Video', new_contest_video_path(contest_id: @contest), class: "btn btn-secondary mb-1 w-50" %>
    <% end %>
    <%#= link_to "Edit", edit_contest_path(@contest), class: "btn btn-secondary mb-1 w-50" %>
  </div>

  <div class="d-flex">
    <% if !@contest.has_ended || (@contest.has_ended && @contest.submissions.empty?)%>
      <%= link_to "Edit", edit_contest_path(@contest), class: "btn btn-secondary mb-1 w-50" %>
    <% end %>
  </div>

  <div class="d-flex">
    <% if !@contest.has_ended && !@contest.paid_for %>
      <a href="#" data-turbolinks="false" class="btn btn-primary mb-1 w-50" onclick="startCheckout()">Deposit Funds</a>
    <% end %>
  </div>

<% end %>


<!--if not vendor:-->
<% if current_user && current_user != @contest.user %>

  <div class="d-flex">
    <% if !@contest.has_ended && !current_user.stripe_id.nil? %>
      <%= link_to 'Enter Contest', new_contest_submission_path(contest_id: @contest), class: "btn btn-success w-50 mb-1" %>
    <% end %>
    <%#= link_to 'Enter Contest', new_contest_submission_path(contest_id: @contest), class: "btn btn-success w-50 mb-1" %>
  </div>

  <div class="d-flex">
    <% if !@contest.has_ended && current_user.stripe_id.nil? %>
      <a href="<%= @stripe_btn_url %>" data-turbolinks="false" class="btn btn-primary w-50 mb-1">Connect Your Stripe
        Account First to Enter!</a>
    <% end %>
  </div>

<% end %>


<div>
  <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button " data-show-count="false">Tweet</a>
  <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</div>

<% if !@videos.empty? %>
  <div class="page-heading">
    <h2>Video Requirements</h2>
  </div>
  <div class="row">
    <% @videos.each do |video| %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-5">
        <div class="card" , id="card-video">
          <img class="card-img-top"<%= link_to image_tag("https://img.youtube.com/vi/#{video.uid}/mqdefault.jpg") %>
          <div class="card-body">
            <h6 class="video-title"><%= video.title %></h6>
            <p>Published at <%= video.published_at.strftime("%d/%m/%Y %H:%M") if video and video.published_at %></p>
            <p>Likes: <%= video.likes if video and !video.likes.nil? %></p>
            <%= link_to 'Watch', "https://www.youtube.com/watch?v=#{video.uid}", target: '_blank', class: "btn btn-secondary", id: "watch-button" %>
            <% if current_user && current_user == @contest.user %>
              <%= link_to "Delete", contest_video_path(contest_id: @contest, id: video.id), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
            <% end %>

          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<% unless @contest.paid_for %>

  <script type="text/javascript" charset="utf-8">
      var stripe = Stripe('<%= Rails.application.credentials.stripe[:publishable_key] %>');

      function startCheckout() {
          stripe.redirectToCheckout({
              // Make the id field from the Checkout Session creation API response
              // available to this file, so you can provide it as parameter here
              // instead of the {{CHECKOUT_SESSION_ID}} placeholder.
              sessionId: '<%= @session.id %>'
          }).then(function (result) {
              // If `redirectToCheckout` fails due to a browser or network
              // error, display the localized error message to your customer
              // using `result.error.message`.
          });
      }
  </script>

<% end %>