Desktop/group22proj-gdpr_requirements/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get '/home/live_chat', to: 'home#live_chat', as: :home_live_chat
  get '/contests/:id/evaluate', to: 'contests#evaluate', as: :contest_evaluate
  post '/contests/:id/evaluate', to: 'contests#submit_ranking', as: :contest_submit_ranking
  get '/connect/oauth', to: 'home#my_contests', as: :contest_connect_stripe

  get 'sessions/create'
  get 'sessions/destroy'

  resources :contests do
    resources :submissions, only: [:index, :new, :create, :destroy]
    resources :videos, only: [:new, :create, :destroy]
  end

  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  root 'home#home'
  get '/leaderboard', to:'home#leaderboard'
  get '/my_contests', to: 'home#my_contests'
  get '/my_submissions', to: 'home#my_submissions'
  get '/home', to: 'home#home'
  get '/users', to: 'home#home'
  #how does submission routing work?
  # get '/submission'
  # get '/like' ??
  #

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Desktop/group22proj-gdpr_requirements/app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :set_submission, only: [:leaderboard, :live_chat, :home]
  # before_action :set_contest, only: [:leaderboard, :live_chat, :home]
  before_action :authenticate_user!, :except => [:home, :leaderboard]

  def home
    @ongoing_contests = Contest.where(paid_for: true, evaluated: false).where("ending_date > '#{Time.now.utc.iso8601}'")
    @contests_evaluated = Contest.where(paid_for: true, evaluated: true).where("ending_date <= '#{Time.now.utc.iso8601}'")
    @total_payout = 0
    payout_total = 0
    @contests_evaluated.each do |contest|
      if contest.payout_amount != 0
        payout_total += contest.payout_amount
      end
    end
    @total_payout = payout_total / 100
  end

  def live_chat
    session[:conversations] ||= []

    @users = User.all.where.not(id: current_user)

    @conversations = Conversation.includes(:recipient, :messages)
                         .find(session[:conversations])
  end

  def leaderboard
    @ranking = User.all.order('contests_won DESC').limit(10)
  end

  def my_submissions
    user = current_user
    total_earnings = 0
    @currently_entered_in = []
    @waiting_for_vendor = []
    @contests_won = []

    # contests the user has entered in
    submissions = Submission.where(user_id: user.id)
    if !submissions.empty?
      @currently_entered_in = submissions.map(&:contest).select { |c| !c.evaluated && c.ending_date > Time.now.utc.iso8601 }

      @waiting_for_vendor = submissions.map(&:contest).select { |c| !c.evaluated && c.paid_for && c.ending_date <= Time.now.utc.iso8601 }

      contest_ended = Contest.where(paid_for: true, evaluated: true).where("ending_date <= '#{Time.now.utc.iso8601}'").order('updated_at DESC')

      @contests_won = contest_ended.where(first_place: user.id)
                          .or(contest_ended.where(second_place: user.id))
                          .or(contest_ended.where(third_place: user.id))

      @contests_won.each do |contest|
        if contest.first_place.to_i == user.id
          total_earnings += contest.first_prize
        elsif !contest.second_place.nil?
          if contest.second_place.to_i == user.id
            total_earnings += contest.second_prize
          elsif !contest.third_place.nil? && contest.third_place.to_i == user.id
            total_earnings += contest.third_prize
          end
        end
      end
    end
    @total_earnings = total_earnings.to_f / 100.0
  end

  def my_contests
    user = current_user
    contests = Contest.all.where(user_id: user.id)
    total_paid_out = 0
    @ongoing_contests = []
    @unpaid_contests = []
    @unranked_contests = []
    @evaluated_contests = []

    if !contests.empty?
      @ongoing_contests = Contest.where(user_id: user.id, paid_for: true, evaluated: false).where("ending_date > '#{Time.now.utc.iso8601}'").order('updated_at DESC')
      @unpaid_contests = Contest.where(user_id: user.id, paid_for: false).order('updated_at DESC')
      @unranked_contests = Contest.where(user_id: user.id, paid_for: true, evaluated: false).where("ending_date <= '#{Time.now.utc.iso8601}'").order('updated_at DESC')
      @evaluated_contests = Contest.where(user_id: user.id, evaluated: true).order('updated_at DESC')

      @evaluated_contests.each do |contest|
        total_paid_out += contest.payout_amount
      end
    end
    @total_paid_out = total_paid_out / 100
    if params.has_key?(:state)
      state = params[:state]
      unless state_matches?(state)
        status 403
        redirect_to contests_path
      end

      # Send the authorization code to Stripe's API.
      code = params[:code]
      begin
        response = Stripe::OAuth.token({
                                           grant_type: 'authorization_code',
                                           code: code,
                                       })
      rescue Stripe::OAuth::InvalidGrantError
        status 400
        redirect_to contests_path
      rescue Stripe::StripeError
        status 500
        redirect_to contests_path
      else
        connected_account_id = response.stripe_user_id
        save_account_id(connected_account_id)
      end
    end
  end

  def state_matches?(state_parameter)
    # Load the same state value that you randomly generated for your OAuth link.
    saved_state = current_user.authenticatable_salt
    saved_state == state_parameter
  end

  def save_account_id(id)
    # Save the connected account ID from the response to your database.
    current_user.stripe_id = id
    user = current_user
    user.stripe_id = id
    user.save
    flash[:notice] = 'Your Stripe Account has been linked!'
  end
  #
  # def set_submission
  #   @submission = Submission.find_by(id: params[:id])
  # end
  #
  # def set_contest
  #   @contest = Contest.find_by(id: params[:contest_id]) || Contest.find(submission_params[:contest_id])
  # end


end

Desktop/group22proj-gdpr_requirements/app/helpers/home_helper.rb
module HomeHelper
end

Desktop/group22proj-gdpr_requirements/app/views/home/home.html.erb
<div class="bg-image"></div>
<%= render 'cookies_eu/consent_banner' %>
<div class="summary-container">
  <div class="row">
    <div class="col-lg-4 col-md-6 p-1 mt-1">
      <div class="card border-white">
        <div class="card text-white bg-dark">
          <div class="row">
            <div class="col-4 text-center mt-4">
              <i class="fas fa-pound-sign fa-5x"></i>
            </div>
            <div class="col-7 text-center summary-texts pt-4 pb-4">
              <h1><%= number_to_currency(@total_payout, unit: "£", separator: ".", delimiter: ",") %></h1>
              <h3><strong>TOTAL PAID OUT</strong></h3>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-md-6 p-1 mt-1">
      <div class="card border-white">
        <div class="card text-white bg-dark">
          <div class="row">
            <div class="col-4 text-center mt-4">
              <i class="fas fa-trophy fa-5x"></i>
            </div>
            <div class="col-7 text-center summary-texts pt-4 pb-4">
              <h1><%=@contests_evaluated.size %></h1>
              <h3><strong>CONTESTS FULFILLED</strong></h3>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-md-6 p-1 mt-1">
      <div class="card border-white">
        <div class="card text-white bg-dark">
          <div class="row">
            <div class="col-4 text-center mt-4">
              <i class="fas fa-clock fa-5x"></i>
            </div>
            <div class="col-7 text-center summary-texts pt-4 pb-4">
              <h1><%=@ongoing_contests.size %></h1>
              <h3><strong>ONGOING CONTESTS</strong></h3>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

Desktop/group22proj-gdpr_requirements/app/views/home/leaderboard.html.erb
<div class="page-heading mt-4">
  <h2>Top 10 Freelancers</h2>
</div>
<table class="table w-100">
  <thead>
  <tr>
    <th scope="col">Username</th>
    <th scope="col">Contests Won</th>
    <th scope="col">Contests Entered</th>
    <th scope="col">Join Date</th>
    <th scope="col">Profession</th>
  </tr>
  </thead>
  <tbody>

  <% @ranking.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.contests_won %></td>
      <td><%= user.contests_entered %></td>
      <td><%= user.created_at.strftime("%m/%d/%Y") %></td>
      <% if user.is_student %>
        <td>Student</td>
      <% else %>
        <td>Professional</td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

Desktop/group22proj-gdpr_requirements/app/views/home/live_chat.html.erb
<div class="row">
  <div class="col-md-9">
    <ul id="conversations-list">
      <% @conversations.each do |conversation| %>
        <%= render 'conversations/conversation', conversation: conversation, user: current_user %>
      <% end %>
    </ul>
  </div>

  <div class="col-md-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Users</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @users.each do |user| %>
            <li><%= link_to user.username, conversations_path(user_id: user), remote: true, method: :post %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

Desktop/group22proj-gdpr_requirements/app/views/home/my_contests.html.erb
<div class="page-heading">
  <h2>Account Summary</h2>
</div>
<div class="row">
  <div class="col-lg-6 col-md-6 p-1 mt-1">
    <div class="card border-white">
      <div class="card text-white bg-dark">
        <div class="row">
          <div class="col-4 text-center mt-4">
            <i class="fas fa-wallet fa-5x"></i>
          </div>
          <div class="col-7 text-center summary-texts pt-4 pb-3">
            <h1><%= number_to_currency(@total_paid_out, unit: "£", separator: ".", delimiter: ",") %></h1>
            <h4><strong>FUNDS PAID OUT</strong></h4>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-6 col-md-6 p-1 mt-1">
    <div class="card border-white">
      <div class="card text-white bg-dark">
        <div class="row">
          <div class="col-5 text-center pr-2 mt-4">
            <i class="fas fa-users fa-5x"></i>
          </div>
          <div class="col-6 text-center summary-texts pt-4 pb-3">
            <h1><%= current_user.created_at.strftime("%m/%d/%Y") %></h1>
            <h4><strong>JOIN DATE</strong></h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="page-heading mt-5">
  <h2>My Contests</h2>
</div>

<% if !@unranked_contests.empty? %>
  <div class="page-heading mt-3">
    <h5>Need Evaluating or have received zero Submissions: <%= @unranked_contests.size %>
      <strong> contest(s) - you may edit past contests that have no submissions.</strong></h5>
  </div>
  <div class="row">
    <% @unranked_contests.each do |contest| %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-3 p-3 mb-1">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= contest.name %></h5>
            <p>
            <h6 class="card-subtitle mb-2 text-muted ">created by: <%= contest.user.username %></h6>
            </p>
            <p class="card-text"><%= contest.description %></p>
            <div>
              <span class="badge badge-price p-2 mt-2">£<%= number_with_delimiter(contest.show_payout, :delimiter => ',', :precision => '2') %></span>
              <% if contest.is_student_only == true %>
                <span class="badge badge-primary p-2 mt-2" style="color: white "><strong>Students Only</strong></span>
              <% end %>
            </div>
            <p class="badge-ending-date">Ends on: <%= contest.ending_on %></span></p>
            <% if current_user %>
              <% if contest.submissions.empty? %>
                <div class="d-flex">
                  <%= link_to "View", contest, class: "btn btn-secondary w-50 mr-2" %>
                  <%= link_to 'Edit', edit_contest_path(contest), class: "btn btn-secondary w-50 mr-2" %>
                </div>
              <% else %>
                <div class="d-flex">
                  <%= link_to "View", contest, class: "btn btn-secondary w-50 mr-2" %>
                  <%= link_to 'Payout', contest_evaluate_path(contest), class: "btn btn-primary w-50 mr-2" %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<% if !@unpaid_contests.empty? %>
  <div class="page-heading mt-2">
    <h5>Inactive: <%= @unpaid_contests.size %> -<strong> Deposit funds to start contests!</strong></h5>
  </div>
  <div class="row">
    <% @unpaid_contests.each do |contest| %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-3 p-3 mb-1">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= contest.name %></h5>
            <h6 class="card-subtitle mb-2 text-muted ">created by: <%= contest.user.username %></h6>
            <p class="card-text"><%= contest.description %></p>
            <div>
              <span class="badge badge-price p-2 mt-2">£<%= number_with_delimiter(contest.show_payout, :delimiter => ',', :precision => '2') %></span>
              <% if contest.is_student_only == true %>
                <span class="badge badge-primary p-2 mt-2" style="color: white "><strong>Students Only</strong></span>
              <% end %>
            </div>
            <p class="badge-ending-date">Ends on: <%= contest.ending_on %></span></p>
            <% if current_user %>
              <div class="d-flex">
                <%= link_to "View", contest, class: "btn btn-secondary w-50 mr-2" %>
                <%= link_to 'Edit', edit_contest_path(contest), class: "btn btn-secondary w-50 mr-2" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<% if !@ongoing_contests.empty? %>
  <div class="page-heading mt-3">
    <h5>Ongoing Contests: <%= @ongoing_contests.size %></h5>
  </div>
  <div class="row">
    <% @ongoing_contests.each do |contest| %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-3 p-3 mb-1">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= contest.name %></h5>
            <p>
            <h6 class="card-subtitle mb-2 text-muted ">created by: <%= contest.user.username %></h6>
            </p>
            <p class="card-text"><%= contest.description %></p>
            <div>
              <span class="badge badge-price p-2 mt-2">£<%= number_with_delimiter(contest.show_payout, :delimiter => ',', :precision => '2') %></span>
              <% if contest.is_student_only == true %>
                <span class="badge badge-primary p-2 mt-2" style="color: white "><strong>Students Only</strong></span>
              <% end %>
            </div>
            <p class="badge-ending-date">Ends on: <%= contest.ending_on %></span></p>
            <% if current_user %>
              <div class="d-flex">
                <%= link_to "View", contest, class: "btn btn-secondary w-50 mr-2" %>
                <%= link_to "Edit", edit_contest_path(contest), class: "btn btn-secondary w-50 mr-2" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>


<% if !@evaluated_contests.empty? %>
  <div class="page-heading mt-3">
    <h5>Previous Contests: <%= @evaluated_contests.size %></h5>
  </div>
  <table class="table">
    <thead>
    <tr>
      <th scope="col">Contest</th>
      <th scope="col">Title</th>
      <th scope="col">Funds Paid</th>
    </tr>
    </thead>
    <tbody>

    <% @evaluated_contests.each do |contest| %>
      <tr>
        <td><%= link_to "View", contest, class: "btn btn-secondary download" %></td>
        <td><%= contest.name %></td>
        <td>£<%= number_with_delimiter(contest.show_payout, :delimiter => ',', :precision => '2') %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>


<%= link_to "Delete Account Here", registration_path(current_user), class: "cancel-link", style: "color: red", data: {confirm: "Are you sure?"}, method: :delete %>

Desktop/group22proj-gdpr_requirements/app/views/home/my_submissions.html.erb
<div class="page-heading">
  <h2>Account Summary</h2>
</div>
<div class="row">
  <div class="col-lg-6 col-md-6 p-1 mt-1">
    <div class="card border-white">
      <div class="card text-white bg-dark">
        <div class="row">
          <div class="col-4 text-center mt-4">
            <i class="fas fa-pound-sign fa-5x"></i>
          </div>
          <div class="col-7 text-center summary-texts pt-4 pb-3">
            <h1><%= number_to_currency(@total_earnings, unit: "£", separator: ".", delimiter: ",") %></h1>
            <h4><strong>TOTAL EARNINGS</strong></h4>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-6 col-md-6 p-1 mt-1">
    <div class="card border-white">
      <div class="card text-white bg-dark">
        <div class="row">
          <div class="col-5 text-center pr-2 mt-4">
            <i class="fas fa-users fa-5x"></i>
          </div>
          <div class="col-6 text-center summary-texts pt-4 pb-3">
            <h1><%= current_user.created_at.strftime("%m/%d/%Y") %></h1>
            <h4><strong>JOIN DATE</strong></h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="page-heading mt-5">
  <h2>My Submissions</h2>
</div>

<% if !@waiting_for_vendor.empty? %>
  <div class="page-heading mt-3">
    <h5>Waiting For Evaluation: <%= @waiting_for_vendor.size %>
      <strong> contest(s) have ended and are waiting to be evaluated!</strong></h5>
  </div>
  <div class="row">
    <% @waiting_for_vendor.each do |contest| %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-3 p-3 mb-1">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= contest.name %></h5>
            <p>
              <h6 class="card-subtitle mb-2 text-muted ">created by: <%= contest.user.username %></h6>
            </p>
            <p class="card-text"><%= contest.description %></p>
            <div>
              <span class="badge badge-price p-2 mt-2">£<%= number_with_delimiter(contest.show_payout, :delimiter => ',', :precision => '2') %></span>
              <% if contest.is_student_only == true %>
                <span class="badge badge-primary p-2 mt-2" style="color: white "><strong>Students Only</strong></span>
              <% end %>
            </div>
            <p class="badge-ending-date">Ends on: <%= contest.ending_on %></span></p>
            <% if current_user %>
              <% if (contest.ending_date <= Date.today() - 7) && !contest.evaluated %>
                <%= link_to "Contact Support for Ranking!", contest, class: "btn btn-danger w-100" %>
              <% else %>
                <%= link_to "View", contest, class: "btn btn-secondary w-100" %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<% if !@currently_entered_in.empty? %>
  <div class="page-heading mt-3">
    <h5>Currently Entered in: <%= @currently_entered_in.size %> Contests</h5>
  </div>
  <div class="row">
    <% @currently_entered_in.each do |contest| %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-3 p-3 mb-1">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= contest.name %></h5>
            <p>
              <h6 class="card-subtitle mb-2 text-muted ">created by: <%= contest.user.username %></h6>
            </p>
            <p class="card-text"><%= contest.description %></p>
            <div>
              <span class="badge badge-price p-2 mt-2">£<%= number_with_delimiter(contest.show_payout, :delimiter => ',', :precision => '2') %></span>
              <% if contest.is_student_only == true %>
                <span class="badge badge-primary p-2 mt-2" style="color: white "><strong>Students Only</strong></span>
              <% end %>
            </div>
            <p class="badge-ending-date">Ends on: <%= contest.ending_on %></span></p>
            <% if current_user %>
              <%= link_to "View", contest, class: "btn btn-secondary w-100" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<% if !@contests_won.empty? %>
  <div class="page-heading mt-3">
    <h5>Contests Won: <%= @contests_won.size %></h5>
  </div>
  <table class="table">
    <thead>
    <tr>
      <th scope="col">Contest</th>
      <th scope="col">Title</th>
      <th scope="col">Place</th>
      <th scope="col">Payout</th>
    </tr>
    </thead>
    <tbody>

    <% @contests_won.each do |contest| %>
      <tr>
        <td><%= link_to "View", contest, class: "btn btn-secondary download" %></td>
        <td><%= contest.name %></td>
        <% if contest.first_place == current_user.id %>
          <td>1st</td>
          <td>£<%= number_with_delimiter(contest.show_first_prize, :delimiter => ',', :precision => '2') %></td>
        <% elsif contest.second_place == current_user.id %>
          <td>2nd</td>
          <td>£<%= number_with_delimiter(contest.show_second_prize, :delimiter => ',', :precision => '2') %></td>
        <% else %>
          <td>3rd</td>
          <td>£<%= number_with_delimiter(contest.show_third_prize, :delimiter => ',', :precision => '2') %></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to "Delete Account Here", registration_path(current_user), class: "cancel-link", style: "color: red", data: {confirm: "Are you sure?"}, method: :delete %>