Desktop/group22proj-gdpr_requirements/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get '/home/live_chat', to: 'home#live_chat', as: :home_live_chat
  get '/contests/:id/evaluate', to: 'contests#evaluate', as: :contest_evaluate
  post '/contests/:id/evaluate', to: 'contests#submit_ranking', as: :contest_submit_ranking
  get '/connect/oauth', to: 'home#my_contests', as: :contest_connect_stripe

  get 'sessions/create'
  get 'sessions/destroy'

  resources :contests do
    resources :submissions, only: [:index, :new, :create, :destroy]
    resources :videos, only: [:new, :create, :destroy]
  end

  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  root 'home#home'
  get '/leaderboard', to:'home#leaderboard'
  get '/my_contests', to: 'home#my_contests'
  get '/my_submissions', to: 'home#my_submissions'
  get '/home', to: 'home#home'
  get '/users', to: 'home#home'
  #how does submission routing work?
  # get '/submission'
  # get '/like' ??
  #

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Desktop/group22proj-gdpr_requirements/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs

    devise_parameter_sanitizer.permit(:sign_up, keys: [:is_student])
    devise_parameter_sanitizer.permit(:account_update, keys: [:is_student])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_rating])
    devise_parameter_sanitizer.permit(:account_update, keys: [:user_rating])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:admin])
    devise_parameter_sanitizer.permit(:account_update, keys: [:admin])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:student_email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:student_email])
  end

  private

  def current_yt_user
    @current_yt_user ||= YtUser.find_by(id: session[:user_id]) if session[:user_id]
  end

  helper_method :current_yt_user
end

Desktop/group22proj-gdpr_requirements/app/helpers/application_helper.rb
module ApplicationHelper
end

Desktop/group22proj-gdpr_requirements/app/views/application/_footer.html.erb
<footer class="footer">
  <!-- if user is logged in, displays footer text in the footer -->
  <% if current_user %>
      <span class="text-muted"><%= t('application._footer.logged_in_message') %>
      </span>
    <%= link_to "Privacy Policy", "/docs/privacy-policy.pdf", target: "_blank" %>
  <% else %>
    <span class="text-muted">Login to begin entering or creating contests!</span>
  <% end %>
</footer>

Desktop/group22proj-gdpr_requirements/app/views/application/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
    <ul class="navbar-nav mr-auto">
      <!-- display links in header on the left -->
      <li class="nav-item">
        <a class="nav-link" <%= link_to t('application._header.home_btn'), root_path %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to 'Browse', contests_path %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to 'Create', new_contest_path %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to t('application._header.leaderboard'), leaderboard_path %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to 'Chat', home_live_chat_path %></a>
      </li>
    </ul>
  </div>
  <div class="mx-auto order-0">
    <p class="navbar-brand mx-auto">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
        <span class="navbar-toggler-icon "></span>
      </button>
  </div>
  <% if current_user %>
    <div class="navbar-brand">Hello,
      <%= current_user.username %>.
    </div>
  <% else %>
    <div class="navbar-brand">Welcome!</div>
  <% end %>
  <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
    <ul class="navbar-nav ml-auto">
      <% if current_user %>
        <div class="dropdown">
          <button class="btn dropdown-toggle float" type="button" data-toggle="dropdown">Account Summary</button>
          <div class="dropdown-menu">
            <a class="dropdown-item" id="my-submissions" , <%= link_to 'My Submissions', my_submissions_path %> </a>
            <a class="dropdown-item" id="my-contests" , <%= link_to 'My Contests', my_contests_path %> </a>
          </div>
        </div>
        <% if current_yt_user %>
          <li> <%= current_yt_user.name %></li>
          <li><a class="nav-link"<%= link_to 'Log Out Youtube', logout_path, method: :delete %></a></li>
        <% else %>
          <li><a class="nav-link"<%= link_to 'Connect My Youtube', '/auth/google_oauth2' %></a></li>

        <% end %>
        <li>
          <a class="nav-link"  <%= link_to 'Log Out', destroy_user_session_path, method: :delete %> </a>
        </li>
      <% else %>
        <li>
          <a class="nav-link"  <%= link_to 'Login', new_user_session_path %> </a>
        </li>
        <li>
          <a class="nav-link"  <%= link_to 'Sign up', new_user_registration_path %> </a>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

Desktop/group22proj-gdpr_requirements/app/views/application/_secondary_header.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-white border-top my-3 border-bottom my-3">
  <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse3">
    <ul class="navbar-nav mr-auto float-right ">
      <!-- display links in header on the left -->
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Art & Illustration", contests_path(category: "Art & Illustration") %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Music & Audio", contests_path(category: "Music & Audio") %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Programming & Tech", contests_path(category: "Programming & Tech") %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Video & Animation", contests_path(category: "Video & Animation") %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Graphics & Design", contests_path(category: "Graphics & Design") %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Lifestyle", contests_path(category: "Lifestyle") %></a>
      </li>
    </ul>
  </div>
  <div class="mx-auto order-0">
    <p class="navbar-brand mx-auto">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse3">
        <span class="navbar-toggler-icon "></span>
      </button>
  </div>
  <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
    <ul class="navbar-nav ml-right">
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Writing", contests_path(category: "Writing") %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Translation", contests_path(category: "Translation") %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Marketing", contests_path(category: "Marketing") %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Non-Profit", contests_path(category: "Non-Profit") %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Other", contests_path(category: "Other") %></a>
      </li>
    </ul>
  </div>
</nav>