Desktop/group22proj-gdpr_requirements/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get '/home/live_chat', to: 'home#live_chat', as: :home_live_chat
  get '/contests/:id/evaluate', to: 'contests#evaluate', as: :contest_evaluate
  post '/contests/:id/evaluate', to: 'contests#submit_ranking', as: :contest_submit_ranking
  get '/connect/oauth', to: 'home#my_contests', as: :contest_connect_stripe

  get 'sessions/create'
  get 'sessions/destroy'

  resources :contests do
    resources :submissions, only: [:index, :new, :create, :destroy]
    resources :videos, only: [:new, :create, :destroy]
  end

  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  root 'home#home'
  get '/leaderboard', to:'home#leaderboard'
  get '/my_contests', to: 'home#my_contests'
  get '/my_submissions', to: 'home#my_submissions'
  get '/home', to: 'home#home'
  get '/users', to: 'home#home'
  #how does submission routing work?
  # get '/submission'
  # get '/like' ??
  #

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Desktop/group22proj-gdpr_requirements/app/models/submission.rb
class Submission < ApplicationRecord
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  has_one :feedback
  belongs_to :contest
  belongs_to :user
  has_many :likes
  validates :contest_id, :user, :attachment, presence: true
#rwar
end

Desktop/group22proj-gdpr_requirements/app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:destroy, :index]
  before_action :set_contest, only: [:new, :create]
  before_action :authenticate_user!


  # GET /submissions
  # GET /submissions.json
  def index
    @contest = Contest.find_by(id: params[:contest_id])
    @submissions = Submission.all.where(contest_id: @contest.id).order("created_at")
    @user_submission = Submission.where(contest_id: @contest.id, user_id: current_user.id)
  end

  # GET /submissions/new
  def new
    @submission = @contest.submissions.new
    @submission.user = current_user

    user_submission = Submission.where(contest_id: @contest.id, user_id: @submission.user.id)
    respond_to do |format|
      if !user_submission.empty?
        format.html { redirect_to contests_path, alert: 'You are already entered into this contest. Please delete your current submission in View Entries page to upload a different submission.' }
      elsif @contest.is_student_only && !@submission.user.is_student
        format.html { redirect_to contests_path, alert: 'Only students are allowed to enter this contest.' }
      elsif @submission.user.stripe_id.nil?
        format.html { redirect_to contests_path, alert: 'You must connect your Stripe account before entering a contest.' }
      else
        format.html { render :new }
      end
    end
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission = @contest.submissions.new(submission_params)
    @submission.user = current_user
    user_submission = Submission.where(contest_id: @contest.id, user_id: @submission.user.id)
    respond_to do |format|
      if user_submission.empty?
        if @submission.save
          @submission.user.contests_entered += 1
          @submission.user.save
          format.html { redirect_to contest_submissions_path, notice: 'Your submission has been successfully uploaded to this contest.' }
        end
      else
        format.html { redirect_to contests_path, alert: 'You are already entered into this contest!' }
      end
    end
  end

  # # PATCH/PUT /submissions/1
  # # PATCH/PUT /submissions/1.json
  # def update
  #   respond_to do |format|
  #     if @submission.update(submission_params)
  #       format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
  #     else
  #       format.html { render :edit }
  #     end
  #   end
  # end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @contest = @submission.contest
    @submission.user = current_user
    respond_to do |format|
      if @contest.has_ended
        format.html { redirect_to contest_submissions_path, alert: 'You cannot remove your submission after a contest has ended.' }
      else
        @submission.destroy
        @submission.user.contests_entered -= 1
        @submission.user.save
        format.html { redirect_to contest_submissions_path, notice: 'You have successfully removed your submission from this contest.' }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_submission
    @submission = Submission.find_by(id: params[:id])
  end

  def set_contest
    @contest = Contest.find_by(id: params[:contest_id]) || Contest.find(submission_params[:contest_id])
  end

  # Only allow a list of trusted parameters through.
  def submission_params
    params.require(:submission).permit(:contest_id, :user_id, :attachment)
  end
end

Desktop/group22proj-gdpr_requirements/app/helpers/submissions_helper.rb
module SubmissionsHelper
end

Desktop/group22proj-gdpr_requirements/app/views/submissions/_form.html.erb
<%= form_with(model: [@contest, submission], local: true) do |form| %>

  <% if submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
        <% submission.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <%= form.hidden_field :user_id, :value => current_user.id %>
  <%= form.hidden_field :contest_id %>

  <div class="custom-file">
    <%= form.label :attachment%>
    <%= form.file_field :attachment %>
  </div>


  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-primary", id: "upload-submission"%>
  </div>
<% end %>

Desktop/group22proj-gdpr_requirements/app/views/submissions/edit.html.erb
<h2>Editing Submission</h2>

<%= render 'form', submission: @submission %>

<%= link_to 'Show', @submission %> |

Desktop/group22proj-gdpr_requirements/app/views/submissions/index.html.erb
<div class="page-heading">
  <h2>Current Submissions</h2>
</div>

<% if current_user && current_user != @contest.user && !@contest.has_ended %>
  <% if @user_submission.empty? %>
    <%= link_to 'Upload a Submission to Enter', new_contest_submission_path, class: "btn btn-primary mt-1 mb-1" %>
  <% else %>
    <h6><strong>You are already entered into this contest. Please delete your current submission to upload
      a different one.</strong></h6>
  <% end %>
<% end %>


<div class="submissions-table">
  <table class="table">
    <thead>
    <tr>
      <th scope="col">No.</th>
      <th scope="col">Username</th>
      <th scope="col">Submission Date</th>
      <th scope="col">View</th>
      <th scope="col">Delete</th>
    </tr>
    </thead>
    <tbody>

    <% @submissions.each do |submission| %>
      <tr>
        <td><%= submission.id %></td>
        <td><%= submission.user.username %></td>
        <td><%= submission.created_at.strftime("%d/%m/%Y") %></td>
        <% if current_user && current_user == submission.user %>
          <td><%= link_to "Download", submission.attachment_url, class: "btn btn-secondary download" %></td>
          <td> <%= link_to "Remove", contest_submission_path(id: submission.id), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %></td>
        <% else %>
          <td>No Permission</td>
          <td>No Permission</td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

Desktop/group22proj-gdpr_requirements/app/views/submissions/new.html.erb
<div class="page-heading">
  <h2>Enter Contest</h2>
</div>

<%= render 'form', submission: @submission %>